const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const priceModule={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/dealerPricing.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:priceModule.exports});
const {monthlyInventoryPrice}=priceModule.exports;
test('Small dealer and lot VAT-inclusive boundaries',()=>{assert.equal(monthlyInventoryPrice('small',10),1000);assert.equal(monthlyInventoryPrice('small',1),100);assert.equal(monthlyInventoryPrice('lot',0),2000);assert.equal(monthlyInventoryPrice('lot',11),2000);assert.equal(monthlyInventoryPrice('lot',40),2000);assert.equal(monthlyInventoryPrice('lot',41),2050);assert.throws(()=>monthlyInventoryPrice('small',11));assert.throws(()=>monthlyInventoryPrice('lot',-1));assert.throws(()=>monthlyInventoryPrice('small',1.5));});
function harness(response){const calls=[];let handler;const db={rpc:async(name,args)=>{calls.push({name,args});return {data:name==='switchapp_payment_config'?{terminal:195940,api_name:'test',cron_secret:'secret'}:null,error:null};},auth:{getUser:async()=>({error:true,data:{user:null}})},from:()=>({update:values=>({eq:async()=>{calls.push({update:values});return{data:null,error:null};}})})};
const context={createClient:()=>db,Deno:{env:{get:()=> 'https://example.supabase.co'},serve:f=>handler=f},fetch:async()=>{calls.push({fetch:true});return {ok:true,json:async()=>response};},AbortSignal,URL,URLSearchParams,Request,Response,Set,console,expose:null};
let source=fs.readFileSync('supabase/functions/dealer-billing/index.ts','utf8').replace(/^import .*;\r?\n/,'')+'\nglobalThis.expose = {verifySetup};';
vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,context);
return{verify:context.expose.verifySetup,calls,handler};}
const order={id:'11111111-1111-4111-8111-111111111111',low_profile_id:'22222222-2222-4222-8222-222222222222',amount_agorot:300000,status:'pending'};
function result(){return{ResponseCode:0,ReturnValue:order.id,LowProfileId:order.low_profile_id,TerminalNumber:195940,Operation:'ChargeAndCreateToken',TranzactionId:123456,TranzactionInfo:{ResponseCode:0,Amount:3000,CoinId:1},TokenInfo:{Token:'test-token-not-real',CardMonth:12,CardYear:2028},DocumentInfo:{ResponseCode:0,DocumentNumber:99}};}
test('Verified setup saves token only after successful provider validation',async()=>{const h=harness(result());assert.equal(await h.verify(order,{terminal:195940}),'paid');assert.equal(h.calls[1].name,'confirm_dealer_setup');assert.equal(h.calls[1].args.p_expiration,'1228');});
test('Amount mismatch never activates subscription',async()=>{const r=result();r.TranzactionInfo.Amount=30;const h=harness(r);await assert.rejects(h.verify(order,{terminal:195940}));assert.equal(h.calls.length,1);});
test('Forged order reference never activates subscription',async()=>{const r=result();r.ReturnValue='other';const h=harness(r);await assert.rejects(h.verify(order,{terminal:195940}));});
test('Failed provider response does not activate',async()=>{const r=result();r.ResponseCode=42;const h=harness(r);assert.equal(await h.verify(order,{terminal:195940}),'pending');assert.equal(h.calls.length,1);});
test('Paid order is idempotent without provider calls',async()=>{const h=harness(result());assert.equal(await h.verify({...order,status:'paid'},{terminal:195940}),'paid');assert.equal(h.calls.length,0);});
test('Missing token requires review and never charges again',async()=>{const r=result();delete r.TokenInfo;const h=harness(r);assert.equal(await h.verify(order,{terminal:195940}),'review');assert.equal(h.calls[1].update.status,'review');});
test('Anonymous checkout and untrusted scheduler are rejected',async()=>{const h=harness(result());assert.equal((await h.handler(new Request('https://example.test/functions/v1/dealer-billing',{method:'POST',body:'{}'}))).status,401);assert.equal((await h.handler(new Request('https://example.test/functions/v1/dealer-billing?action=close-month',{method:'POST',body:'{}'}))).status,401);assert.equal(h.calls.some(c=>c.fetch),false);});
